---
- name: Install package with nodenv
  command: npm install -g {{ item.name }}
  args:
    creates: "{{ nodenv_packages_shims }}/{{ item.bin | default(item.name) }}"
  become: true
  become_user: "{{ nodenv_packages_user }}"
  environment:
    NODENV_VERSION: "{{ nodenv_packages_node_version }}"
    PATH: "{{ nodenv_packages_shims }}:{{ ansible_env.PATH }}"
  with_items: "{{ nodenv_packages }}"
- name: Rehash nodenv
  command: "{{ nodenv_packages_bin }} rehash"
  become: true
  become_user: "{{ nodenv_packages_user }}"
  changed_when: false
